image: python:latest

services:
  - postgres:latest

#variables:
#  POSTGRES_DB: ci

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python -V
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo apt-get -yq update
  - sudo apt-get -yq install python3.4 python3.4-dev python3.6 python3.6-dev
  - pip install -r requirements-test.txt

test:
#  variables:
#    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/$POSTGRES_DB"
  script:
  - ./test.sh
